default_platform(:android)

platform :android do
  desc "Builds the AAB and uploads it to Google Play"
  lane :upload do
    # Build the AAB (if not already built)
    sh "flutter build appbundle --release"

    upload_to_play_store(
      track: "production",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      json_key: ENV["PLAY_STORE_JSON"],
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
