// Mocks generated by Mockito 5.4.4 from annotations
// in parion/test/integration/auth_flow_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:parion/models/security/security_models.dart' as _i2;
import 'package:parion/models/user.dart' as _i11;
import 'package:parion/services/auth/interfaces/auth_orchestrator_interface.dart'
    as _i6;
import 'package:parion/services/auth/interfaces/biometric_auth_interface.dart'
    as _i8;
import 'package:parion/services/auth/interfaces/data_sync_interface.dart'
    as _i5;
import 'package:parion/services/auth/interfaces/security_controller_interface.dart'
    as _i4;
import 'package:parion/services/auth/interfaces/session_manager_interface.dart'
    as _i3;
import 'package:parion/services/auth/interfaces/social_login_interface.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthState_0 extends _i1.SmartFake implements _i2.AuthState {
  _FakeAuthState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthResult_1 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSessionState_2 extends _i1.SmartFake implements _i3.SessionState {
  _FakeSessionState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSecurityConfig_3 extends _i1.SmartFake
    implements _i2.SecurityConfig {
  _FakeSecurityConfig_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSecurityValidationResult_4 extends _i1.SmartFake
    implements _i4.SecurityValidationResult {
  _FakeSecurityValidationResult_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncResult_5 extends _i1.SmartFake implements _i5.SyncResult {
  _FakeSyncResult_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IAuthOrchestrator].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthOrchestrator extends _i1.Mock implements _i6.IAuthOrchestrator {
  MockIAuthOrchestrator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<_i2.AuthState> get authStateStream => (super.noSuchMethod(
        Invocation.getter(#authStateStream),
        returnValue: _i7.Stream<_i2.AuthState>.empty(),
      ) as _i7.Stream<_i2.AuthState>);

  @override
  _i2.AuthState get currentAuthState => (super.noSuchMethod(
        Invocation.getter(#currentAuthState),
        returnValue: _FakeAuthState_0(
          this,
          Invocation.getter(#currentAuthState),
        ),
      ) as _i2.AuthState);

  @override
  _i7.Future<_i2.AuthResult> authenticate(
    _i2.AuthMethod? method,
    Map<String, dynamic>? credentials,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [
            method,
            credentials,
          ],
        ),
        returnValue: _i7.Future<_i2.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #authenticate,
            [
              method,
              credentials,
            ],
          ),
        )),
      ) as _i7.Future<_i2.AuthResult>);

  @override
  _i7.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.AuthResult> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [email],
        ),
        returnValue: _i7.Future<_i2.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #sendPasswordResetEmail,
            [email],
          ),
        )),
      ) as _i7.Future<_i2.AuthResult>);

  @override
  _i7.Future<bool> isAuthenticated() => (super.noSuchMethod(
        Invocation.method(
          #isAuthenticated,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> requiresSensitiveAuth() => (super.noSuchMethod(
        Invocation.method(
          #requiresSensitiveAuth,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i2.AuthResult> authenticateForSensitiveOperation(
    _i2.AuthMethod? method,
    Map<String, dynamic>? credentials,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticateForSensitiveOperation,
          [
            method,
            credentials,
          ],
        ),
        returnValue: _i7.Future<_i2.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #authenticateForSensitiveOperation,
            [
              method,
              credentials,
            ],
          ),
        )),
      ) as _i7.Future<_i2.AuthResult>);

  @override
  _i7.Future<void> recordActivity() => (super.noSuchMethod(
        Invocation.method(
          #recordActivity,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> onAppBackground() => (super.noSuchMethod(
        Invocation.method(
          #onAppBackground,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> onAppForeground() => (super.noSuchMethod(
        Invocation.method(
          #onAppForeground,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [IBiometricAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBiometricAuthService extends _i1.Mock
    implements _i8.IBiometricAuthService {
  MockIBiometricAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<bool> isAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isAvailable,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<_i2.BiometricType>> getAvailableTypes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableTypes,
          [],
        ),
        returnValue:
            _i7.Future<List<_i2.BiometricType>>.value(<_i2.BiometricType>[]),
      ) as _i7.Future<List<_i2.BiometricType>>);

  @override
  _i7.Future<_i2.AuthResult> authenticate({
    required String? reason,
    String? localizedFallbackTitle,
    String? cancelButtonText,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [],
          {
            #reason: reason,
            #localizedFallbackTitle: localizedFallbackTitle,
            #cancelButtonText: cancelButtonText,
          },
        ),
        returnValue: _i7.Future<_i2.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #authenticate,
            [],
            {
              #reason: reason,
              #localizedFallbackTitle: localizedFallbackTitle,
              #cancelButtonText: cancelButtonText,
            },
          ),
        )),
      ) as _i7.Future<_i2.AuthResult>);

  @override
  _i7.Future<void> enableBiometric() => (super.noSuchMethod(
        Invocation.method(
          #enableBiometric,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> disableBiometric() => (super.noSuchMethod(
        Invocation.method(
          #disableBiometric,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> isBiometricEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isBiometricEnabled,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ISessionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockISessionManager extends _i1.Mock implements _i3.ISessionManager {
  MockISessionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<_i3.SessionState> get sessionStateStream => (super.noSuchMethod(
        Invocation.getter(#sessionStateStream),
        returnValue: _i7.Stream<_i3.SessionState>.empty(),
      ) as _i7.Stream<_i3.SessionState>);

  @override
  _i3.SessionState get currentSessionState => (super.noSuchMethod(
        Invocation.getter(#currentSessionState),
        returnValue: _FakeSessionState_2(
          this,
          Invocation.getter(#currentSessionState),
        ),
      ) as _i3.SessionState);

  @override
  _i7.Future<bool> createSession({
    required _i2.SessionData? sessionData,
    required _i2.AuthMethod? authMethod,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSession,
          [],
          {
            #sessionData: sessionData,
            #authMethod: authMethod,
            #metadata: metadata,
          },
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> extendSession() => (super.noSuchMethod(
        Invocation.method(
          #extendSession,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> invalidateSession() => (super.noSuchMethod(
        Invocation.method(
          #invalidateSession,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> isSessionValid() => (super.noSuchMethod(
        Invocation.method(
          #isSessionValid,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> requiresReauth() => (super.noSuchMethod(
        Invocation.method(
          #requiresReauth,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> recordActivity() => (super.noSuchMethod(
        Invocation.method(
          #recordActivity,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> onAppBackground() => (super.noSuchMethod(
        Invocation.method(
          #onAppBackground,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> onAppForeground() => (super.noSuchMethod(
        Invocation.method(
          #onAppForeground,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setSensitiveScreenState(bool? isSensitive) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSensitiveScreenState,
          [isSensitive],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<Duration?> getSessionRemainingTime() => (super.noSuchMethod(
        Invocation.method(
          #getSessionRemainingTime,
          [],
        ),
        returnValue: _i7.Future<Duration?>.value(),
      ) as _i7.Future<Duration?>);

  @override
  _i7.Future<bool> updateSecurityConfig(_i2.SecurityConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSecurityConfig,
          [config],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ISocialLoginService].
///
/// See the documentation for Mockito's code generation for more information.
class MockISocialLoginService extends _i1.Mock
    implements _i9.ISocialLoginService {
  MockISocialLoginService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.AuthResult> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i7.Future<_i2.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #signInWithGoogle,
            [],
          ),
        )),
      ) as _i7.Future<_i2.AuthResult>);

  @override
  _i7.Future<_i2.AuthResult> signInWithApple() => (super.noSuchMethod(
        Invocation.method(
          #signInWithApple,
          [],
        ),
        returnValue: _i7.Future<_i2.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #signInWithApple,
            [],
          ),
        )),
      ) as _i7.Future<_i2.AuthResult>);

  @override
  _i7.Future<bool> isAppleSignInAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isAppleSignInAvailable,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i2.AuthResult> linkAccount(
    String? provider,
    Map<String, dynamic>? credentials,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkAccount,
          [
            provider,
            credentials,
          ],
        ),
        returnValue: _i7.Future<_i2.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #linkAccount,
            [
              provider,
              credentials,
            ],
          ),
        )),
      ) as _i7.Future<_i2.AuthResult>);

  @override
  _i7.Future<void> unlinkAccount(String? provider) => (super.noSuchMethod(
        Invocation.method(
          #unlinkAccount,
          [provider],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<String>> getLinkedProviders() => (super.noSuchMethod(
        Invocation.method(
          #getLinkedProviders,
          [],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<void> signOutAll() => (super.noSuchMethod(
        Invocation.method(
          #signOutAll,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ISecurityController].
///
/// See the documentation for Mockito's code generation for more information.
class MockISecurityController extends _i1.Mock
    implements _i4.ISecurityController {
  MockISecurityController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<_i2.SecurityEvent> get securityEventsStream => (super.noSuchMethod(
        Invocation.getter(#securityEventsStream),
        returnValue: _i7.Stream<_i2.SecurityEvent>.empty(),
      ) as _i7.Stream<_i2.SecurityEvent>);

  @override
  _i7.Future<void> storeSecurely(
    String? key,
    String? value, {
    bool? encrypted = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeSecurely,
          [
            key,
            value,
          ],
          {#encrypted: encrypted},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> retrieveSecurely(
    String? key, {
    bool? encrypted = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #retrieveSecurely,
          [key],
          {#encrypted: encrypted},
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> deleteSecurely(String? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteSecurely,
          [key],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String> encryptForTransmission(String? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #encryptForTransmission,
          [data],
        ),
        returnValue: _i7.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #encryptForTransmission,
            [data],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> decryptReceived(String? encryptedData) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptReceived,
          [encryptedData],
        ),
        returnValue: _i7.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #decryptReceived,
            [encryptedData],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<bool> checkRateLimit(
    String? operation,
    int? maxAttempts,
    Duration? timeWindow,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkRateLimit,
          [
            operation,
            maxAttempts,
            timeWindow,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> logSecurityEvent(_i2.SecurityEvent? event) =>
      (super.noSuchMethod(
        Invocation.method(
          #logSecurityEvent,
          [event],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.SecurityConfig> getSecurityConfig() => (super.noSuchMethod(
        Invocation.method(
          #getSecurityConfig,
          [],
        ),
        returnValue: _i7.Future<_i2.SecurityConfig>.value(_FakeSecurityConfig_3(
          this,
          Invocation.method(
            #getSecurityConfig,
            [],
          ),
        )),
      ) as _i7.Future<_i2.SecurityConfig>);

  @override
  _i7.Future<bool> updateSecurityConfig(_i2.SecurityConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSecurityConfig,
          [config],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i4.SecurityValidationResult> validateSecurityRequirements(
    String? operation,
    Map<String, dynamic>? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateSecurityRequirements,
          [
            operation,
            context,
          ],
        ),
        returnValue: _i7.Future<_i4.SecurityValidationResult>.value(
            _FakeSecurityValidationResult_4(
          this,
          Invocation.method(
            #validateSecurityRequirements,
            [
              operation,
              context,
            ],
          ),
        )),
      ) as _i7.Future<_i4.SecurityValidationResult>);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DataSyncInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataSyncInterface extends _i1.Mock implements _i5.DataSyncInterface {
  MockDataSyncInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<_i5.SyncStatus> get syncStatusStream => (super.noSuchMethod(
        Invocation.getter(#syncStatusStream),
        returnValue: _i7.Stream<_i5.SyncStatus>.empty(),
      ) as _i7.Stream<_i5.SyncStatus>);

  @override
  bool get isOnline => (super.noSuchMethod(
        Invocation.getter(#isOnline),
        returnValue: false,
      ) as bool);

  @override
  bool get isSyncing => (super.noSuchMethod(
        Invocation.getter(#isSyncing),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i5.SyncResult> syncUserProfile(_i11.User? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncUserProfile,
          [user],
        ),
        returnValue: _i7.Future<_i5.SyncResult>.value(_FakeSyncResult_5(
          this,
          Invocation.method(
            #syncUserProfile,
            [user],
          ),
        )),
      ) as _i7.Future<_i5.SyncResult>);

  @override
  _i7.Future<_i5.SyncResult> syncAllUserData(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncAllUserData,
          [userId],
        ),
        returnValue: _i7.Future<_i5.SyncResult>.value(_FakeSyncResult_5(
          this,
          Invocation.method(
            #syncAllUserData,
            [userId],
          ),
        )),
      ) as _i7.Future<_i5.SyncResult>);

  @override
  _i7.Future<_i5.SyncResult> syncPendingOperations() => (super.noSuchMethod(
        Invocation.method(
          #syncPendingOperations,
          [],
        ),
        returnValue: _i7.Future<_i5.SyncResult>.value(_FakeSyncResult_5(
          this,
          Invocation.method(
            #syncPendingOperations,
            [],
          ),
        )),
      ) as _i7.Future<_i5.SyncResult>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
